Month 12/step 1
Volkova-fe/algososh pull request #1
Opened 2022-11-04 14:51 UTC by Volkova-fe

2022-11-04 16:30 UTC, ArslanDev666 requested changes
## Code Review

Здравствуйте!

Работа проделана огромная.

### **Вы молодец!**

- Сборка и запуск проекта выполняются без ошибок;
- Реализованы все алгоритмы.

### **Но есть несколько замечаний, которые нужно исправить:**

- По чек-листу: во время анимации алгоритма на активной кнопке отображается прелоадер, остальные кнопки и поля ввода неактивны (состояние disabled) до завершения работы алгоритма; Доработайте во всех алгоритмах.

- "Магические" значения лучше вынести в константу. Имена констант принято записывать в стиле UPPER_CASE. (Отметил места в коде);

- Приложение не должно содержать `console.log` и `debugger-ов`.

- Стек:

  - https://yadi.sk/d/ghSd960mQcwOog, сделайте ограничение на добавление элементов.

- Связный список:

  - реализован класс LinkedList с методами prepend, append, addByIndex, deleteByIndex, deleteHead, deleteTailи toArray. Класс является дженериком, который принимает как параметр тип элемента списка; У вас есть несколько похожих методов, просто переименуйте их, как сказано в чек-листе.

  - Нужно чтобы была возможность удалять элемент по индексу, если в поле значения пусто. https://yadi.sk/d/HlR45k1RuiT27w

  - https://yadi.sk/d/l2CjYTUpGOICQg, если полностью удалить элементы, и попытаться добавить новый, то возникает бесконечный `loading`.

### **Сделает код лучше:**

- Лучше реализовывать удаление таймера/интервала при размонтировании компонента, иначе возможны ошибки/баги когда компонент размонтируется, а таймер всё равно сработает.

- Перед отправкой работы убедитесь в том, что весь неиспользуемый код удален.

- Стоит обращать внимание на предупреждения в терминале, в котором запущен проект. Это хорошие рекомендации, которых следовало бы придерживаться. В противном случае, лучше отключить линтер у строки (куска кода) eslint-disable. Так же добавить комментарий (TODO), объясняющий причину блокировки линтера в данном месте. Суть в том, что мы стараемся писать более чистый код, а если видим, что порой выскакивают предупреждения того же линтера, то оставляем комментарий, объясняющий причину. В коммерческой разработке, когда есть целая команда разработчиков, работающих над одним проектом, эта рекомендация послужит правилом хорошего тона. Неплохая статься по поводу локального отключения линтера: https://learn.coderslang.com/ru/0023-eslint-disable-for-specific-lines-files-and-folders

- В некоторых местах нарушено форматирование кода, проблемы с отступами и в некоторых местах слишком длинные строки, что затрудняет чтение кода. Об оформлении кода можно почитать здесь https://learn.javascript.ru/coding-style. Постарайтесь использовать автоматическое форматирование, это сильно экономит время. Одно из наиболее популярных дополнений для форматирования кода - Prettier (https://prettier.io/)

### **_Подробно эти и более мелкие замечания, отмечены в коде._**

#### **Хочу напомнить, что работа может быть принята, только после исправления всех "Надо исправить". Перед отправкой на ревью, проверьте работоспособность проекта и наличие возможных ошибок в консоли браузера (кнопка F12).**

2022-11-04 16:30 UTC, ArslanDev666 commented on src/components/fibonacci-page/utils.ts
> +export const fib = (n: number, memo: Record<number, number> = {}): number => {
**Можно лучше:** Лучше переименовать функцию в `getFibonacciNumbers`) требование чек-листа.

2022-11-04 16:30 UTC, ArslanDev666 commented on src/components/fibonacci-page/utils.ts
> +};
**Можно лучше:** Возможно лучше будет использовать такой алгоритм: 

```js
export function getFibonacciNumbers(count: number) {
  const fibonacciNumbers = [1, 1];
  for (let i = 2; i <= count; i++) {
    const a = fibonacciNumbers[i - 1];
    const b = fibonacciNumbers[i - 2];
    fibonacciNumbers.push(a + b);
  }
  return fibonacciNumbers;
}

```

2022-11-04 16:30 UTC, ArslanDev666 commented on src/components/fibonacci-page/fibonacci-page.tsx
> +    const number = e.currentTarget.value.trim();
**Вы молодец:** Это отлично, что вы учитываете и такой вариант, когда у нас могут быть пробелы по бокам строки.

2022-11-04 16:30 UTC, ArslanDev666 commented on src/components/fibonacci-page/fibonacci-page.tsx
> +  const inputLimit = 1 <= inputValue && inputValue <= 19 ? false : true;
**Надо исправить:** 

Здесь и далее.
Нужно вынести магическое значение `19` в константу и переиспользовать её.

2022-11-04 16:30 UTC, ArslanDev666 commented on src/components/fibonacci-page/fibonacci-page.tsx
> +          maxLength={2}
**Надо исправить:** 

Нужно вынести магическое значение `2` в константу.

2022-11-04 16:30 UTC, ArslanMustafin commented on src/components/list-page/list-page.tsx
> +    }, []);
**Можно лучше:** Немного не понимаю зачем 2 раза присваивать `listArray` - `listArr`.

2022-11-04 16:30 UTC, ArslanDev666 commented on src/components/list-page/class/list-page.ts
> +    constructor(initialArray: T[]) {
**Надо исправить:** Хоть у вас и есть параметр в конструкторе, но вы его не используете. Возможно всё таки можно как-то упросить вашу логику, используя этот начальный параметр).

2022-11-04 16:30 UTC, ArslanDev666 commented on src/components/list-page/class/list-page.ts
> +        } else {
При использовании return внутри `if`, оператор `else` можно опустить, т.к. если `if` выполнится, то будет возврат из функции и код под блоком `if` выполнен	не будет:
```js
	if (someCondition) {
		return value;
	}
	return data;
```
Такой подход называется "ранний возврат" https://habr.com/ru/post/348074/

2022-11-04 16:30 UTC, ArslanDev666 commented on src/components/list-page/class/list-page.ts
> +            console.log("Enter a valid index");
**Надо исправить:** 

Приложение не должно содержать `console.log` и `debugger-ов`.

2022-11-04 16:30 UTC, ArslanDev666 commented on src/components/list-page/class/list-page.ts
> +            console.log('Enter a valid index');
**Надо исправить:** 

Приложение не должно содержать `console.log` и `debugger-ов`.

2022-11-04 16:30 UTC, ArslanDev666 commented on src/components/sorting-page/sorting-page.tsx
> +                if (direction ? array[j].num < array[maxInd].num : array[j].num > array[maxInd].num) {
**Можно лучше:** Здесь и далее. Стоит создать функции сортировки таким образом, чтобы они возвращали набор шагов и далее при отображении алгоритма добавлять паузы между шагами, а не генерировать паузы непосредственно в алгоритме.

2022-11-04 17:02 UTC, Volkova-fe commented on src/components/sorting-page/sorting-page.tsx
> +                if (direction ? array[j].num < array[maxInd].num : array[j].num > array[maxInd].num) {
> **Можно лучше:** Здесь и далее. Стоит создать функции сортировки таким образом, чтобы они возвращали набор шагов и далее при отображении алгоритма добавлять паузы между шагами, а не генерировать паузы непосредственно в алгоритме.

Я буду максимально благодарна, любому намеку по реализации, очень тяжелый месяц...... но если нет, то буду рыть и все равно поправлю 💜

2022-11-04 17:03 UTC, Volkova-fe commented on src/components/list-page/list-page.tsx
> +    }, []);
> **Можно лучше:** Немного не понимаю зачем 2 раза присваивать `listArray` - `listArr`.

Этот эффект генерировал мне первоначальный массив, который указан в задании🫣

2022-11-05 12:46 UTC, Volkova-fe commented
> ## Code Review
> Здравствуйте!
> 
Лучше реализовывать удаление таймера/интервала при размонтировании компонента, иначе возможны ошибки/баги когда компонент размонтируется, а таймер всё равно сработает.
**
Здравствуйте)

У меня в VS code не было предупреждений линтера, к сожалению, не смогла воспроизвести. 
Форматирование стандартное через editConfig :(
Некоторые вещи из "можно лучше" оставлю на доработку, сейчас не успеваю из-за большой нагрузки

2022-11-05 20:53 UTC, ArslanDev666 requested changes
## Code Review

Здравствуйте!

Замечания с `Можно лучше` - не обязательны для исправления, они просто есть, чтобы студент представлял, что может улучшить его код. Только замечания с пометкой `Надо исправить`, обязательны к исправлению.

### **Вы молодец!**

- Практически все замечания с прошлого ревью были исправлены.

### **Но есть 1 небольшое замечание, которое нужно исправить:**

- Последовательность фиббоначи: при нажатии кнопки «Рассчитать» числа последовательности должны появляться постепенно. Знаю, что у вас уже было это реализовано, но почему-то вы убрали ту реализацию.

### **Сделает код лучше:**

- Стек:
  - https://yadi.sk/d/ghSd960mQcwOog, сделайте ограничение на добавление элементов.

### **_Подробно эти и более мелкие замечания, отмечены в коде._**

2022-11-06 05:41 UTC, ArslanDev666 approved these changes
## Code Review

Здравствуйте!

Все замечания с прошлого ревью были исправлены.

### **Вы молодец!🔥 Работа принята, удачи в дальнейшем обучении!**

2022-11-06 05:41 UTC, ArslanDev666 commented on src/components/fibonacci-page/fibonacci-page.tsx
> +  const justifyStyle = fibArray && fibArray.length < 10 ?
**Можно лучше:** я бы не рекомендовал использовать инлайн стили)) лучше использовать классы, т.к их можно перебить, а инлайн стили можно перебить, только через !important.

2022-11-06 06:09 UTC, merged