Month 13/step 1
Volkova-fe/algososh pull request #3
Opened 2022-11-26 11:05 UTC by Volkova-fe

2022-11-26 12:28 UTC, ArslanDev666 requested changes
## Code Review

Здравствуйте!

### **Вы молодец!**

- Сборка и запуск проекта выполняются без ошибок;
- все юнит-тесты проходят успешно;
- все Snapshots-тесты проходят успешны;

### **Но есть несколько замечаний, которые нужно исправить:**

- Покрытие говорит, что у вас не протестировано поведение компонента `components/ui/button` при разных значениях пропса `sorting`, а также `linkedList`. Чтобы проверить покрытие тестами всех компонентов используйте команду `react-scripts test --coverage --watchAll`. https://yadi.sk/i/mzGtQol-eCiHwA

- cypress:

  - У вас возникли ошибки в list.spec:

    - https://yadi.sk/d/SDbPssiCWpCarw
    - https://yadi.sk/d/qAHI8V_g1cC0XQ
    - https://yadi.sk/d/GgG0gWu3TYqX0Q
    - https://yadi.sk/d/2PwVCjG7fT7zKg

  - У вас возникли ошибки в queue.spec:

    - https://yadi.sk/d/iDarDo4bFQMAkg

  - У вас возникла ошибка в stack.spec:

    - https://yadi.sk/d/yUMKhM_ldHLWZA

  - У вас возникла ошибка в string.spec:

    - https://yadi.sk/d/Yj1GQnwisPvTIQ

  - router.spec, желательно проверять тайтлы, а не просто переходить по ссылкам:

    - у каждой страницы есть свой https://yadi.sk/d/RucYkoSIMSJaLw

### **Сделает код лучше:**

- Стоит обращать внимание на предупреждения в терминале, в котором запущен проект. Это хорошие рекомендации, которых следовало бы придерживаться. В противном случае, лучше отключить линтер у строки (куска кода) eslint-disable. Так же добавить комментарий (TODO), объясняющий причину блокировки линтера в данном месте. Суть в том, что мы стараемся писать более чистый код, а если видим, что порой выскакивают предупреждения того же линтера, то оставляем комментарий, объясняющий причину. В коммерческой разработке, когда есть целая команда разработчиков, работающих над одним проектом, эта рекомендация послужит правилом хорошего тона. Неплохая статься по поводу локального отключения линтера: https://learn.coderslang.com/ru/0023-eslint-disable-for-specific-lines-files-and-folders

Если чуть выше пролистнуть консоль, увидите там что-то такое: https://yadi.sk/d/sB4rwdyaio74Kw.

### **_Подробно эти и более мелкие замечания, отмечены в коде._**

#### **Хочу напомнить, что работа может быть принята, только после исправления всех "Надо исправить". Перед отправкой на ревью, проверьте работоспособность проекта и наличие возможных ошибок в консоли браузера (кнопка F12).**

2022-11-26 12:28 UTC, ArslanDev666 commented on cypress/e2e/string.spec.cy.js
> +				.children().should('have.text', 'h')
**Можно лучше:**
Здесь и в похожих местах.
Попробуйте использовать перебор .each https://docs.cypress.io/api/commands/each

2022-11-26 12:44 UTC, Volkova-fe commented
> ## Code Review
> Здравствуйте!
> 
> ### **Вы молодец!**
> * Сборка и запуск проекта выполняются без ошибок;
> * все юнит-тесты проходят успешно;
> * все Snapshots-тесты проходят успешны;
> 
> ### **Но есть несколько замечаний, которые нужно исправить:**
> * Покрытие говорит, что у вас не протестировано поведение компонента `components/ui/button` при разных значениях пропса `sorting`, а также `linkedList`. Чтобы проверить покрытие тестами всех компонентов используйте команду `react-scripts test --coverage --watchAll`. https://yadi.sk/i/mzGtQol-eCiHwA
> * cypress:
>   
>   * У вас возникли ошибки в list.spec:
>     
>     * https://yadi.sk/d/SDbPssiCWpCarw
>     * https://yadi.sk/d/qAHI8V_g1cC0XQ
>     * https://yadi.sk/d/GgG0gWu3TYqX0Q
>     * https://yadi.sk/d/2PwVCjG7fT7zKg
>   * У вас возникли ошибки в queue.spec:
>     
>     * https://yadi.sk/d/iDarDo4bFQMAkg
>   * У вас возникла ошибка в stack.spec:
>     
>     * https://yadi.sk/d/yUMKhM_ldHLWZA
>   * У вас возникла ошибка в string.spec:
>     
>     * https://yadi.sk/d/Yj1GQnwisPvTIQ
>   * router.spec, желательно проверять тайтлы, а не просто переходить по ссылкам:
>     
>     * у каждой страницы есть свой https://yadi.sk/d/RucYkoSIMSJaLw
> 
> ### **Сделает код лучше:**
> * Стоит обращать внимание на предупреждения в терминале, в котором запущен проект. Это хорошие рекомендации, которых следовало бы придерживаться. В противном случае, лучше отключить линтер у строки (куска кода) eslint-disable. Так же добавить комментарий (TODO), объясняющий причину блокировки линтера в данном месте. Суть в том, что мы стараемся писать более чистый код, а если видим, что порой выскакивают предупреждения того же линтера, то оставляем комментарий, объясняющий причину. В коммерческой разработке, когда есть целая команда разработчиков, работающих над одним проектом, эта рекомендация послужит правилом хорошего тона. Неплохая статься по поводу локального отключения линтера: https://learn.coderslang.com/ru/0023-eslint-disable-for-specific-lines-files-and-folders
> 
> Если чуть выше пролистнуть консоль, увидите там что-то такое: https://yadi.sk/d/sB4rwdyaio74Kw.
> 
> ### **_Подробно эти и более мелкие замечания, отмечены в коде._**
> #### **Хочу напомнить, что работа может быть принята, только после исправления всех "Надо исправить". Перед отправкой на ревью, проверьте работоспособность проекта и наличие возможных ошибок в консоли браузера (кнопка F12).**

не могу воспроизвести ошибки cypress у меня все тесты проходять

2022-11-27 07:06 UTC, ArslanDev666 approved these changes
## Code Review

Здравствуйте!

Все замечания с прошлого ревью были исправлены.

### **Вы молодец! Работа принята, удачи в дальнейшем обучении.**

2022-11-27 07:21 UTC, merged